using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.AI;

public class AgentScript : MonoBehaviour
{
    [SerializeField] Transform target;

    private NavMeshAgent agent;
    public Animator animator;
    Vector3 prevPosition;
    Vector3 deltaPosition;

    void Start()
    {
        target = GameObject.FindGameObjectWithTag("Player").transform; //получени€ объекта игрока

        agent = GetComponent<NavMeshAgent>();//настройка агента navmesh
        agent.updateRotation = false;
        agent.updateUpAxis = false;
    }

    // Update is called once per frame
    void Update()
    {
        agent.SetDestination(target.position);//установить, куда идти врагу(позици€ геро€)


      /*  deltaPosition = agent.nextPosition - prevPosition; // подсчЄт дельты перемещени€

        animator.SetFloat("Horizontal", deltaPosition.x); //установить в состо€ни€х дельту перемещени€
        animator.SetFloat("Vertical", deltaPosition.y);
        if (deltaPosition.x != 0f || deltaPosition.y != 0f) //установить состо€ние скорости при дельта перемещени€ отличного от 0
            animator.SetFloat("Speed", 1f);
        else
            animator.SetFloat("Speed", 0f);
        prevPosition = agent.nextPosition; //сохранени€ позиции как предыдущей*/   //Ќ≈ ”ƒјЋя“№

    }
    
}
